### ISSUE TITLE
Adding etiologies of the inflammation

### ISSUE THREAD

**Issue by Dimarond** [pknight001/python-intermediate-inflammation#12]
Differentiating different types of inflammation: 

-infectious/autoimmune/drug induced/toxins/traumatic

-acute vs chronic  

-under treatment vs no treatment

And seeing how the inflammation markers (if data is avalible) for example C-reactive protein (CRP), erythrocyte sedimentation rate (ESR) and plasma viscosity (PV) are impacted by each type of inflammation.

**Comment by pknight001** [comment]
Perhaps you should read the README.md file...
